version: "3.9"

services:
  sad-backend:
    build:
      context: SADBackend/.
      target: prod-builder
      dockerfile: Dockerfile
    container_name: sad-backend
    expose:
      - "5000"
    ports:
      - "9229:9229"
    restart: always
    depends_on:
      - mongodb
      - nginx
    volumes:
      - ./SADBackend/src:/app/src
      - ./SADBackend/nodemon.json:/app/nodemon.json
      - ./SADBackend/swagger.taml:/app/swagger.json

  nginx:
    container_name: nginx
    build:
      context: Http/.
      dockerfile: DevDockerfile
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
        # Temp opened for debugging
      - target: 2000
        published: 4321
        mode: host
    volumes:
      - nginx_certs:/etc/nginx/certs
    restart: always
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    build:
      context: Http/frontend/.
      dockerfile: DevDockerfile
    ports:
      - "3000:3000" #for nginx and debugging
    volumes:
      - ./Http/frontend/src:/app/src

  mongodb:
    image: mongo:latest
    command: mongod --port 27017
    expose:
      - "27017"
    volumes:
      - mongodb_data_container:/data/db
    container_name: mongodb
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - target: 8081
        published: 8081
        mode: host
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongodb:27017/"
    depends_on:
      - mongodb
      
volumes:
  mongodb_data_container:
  nginx_certs:
