version: "3.9"

services:
  sad-backend:
    build:
      context: SADBackend/.
      target: dist-builder
      dockerfile: Dockerfile
    container_name: sad-backend
    expose:
      - "5000"
    restart: always
    environment:
      - ENV=PROD
    depends_on:
      - mongodb
  nginx:
    container_name: nginx
    build:
      context: Http/.
      dockerfile: Dockerfile
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - nginx_certs:/etc/nginx/certs
    environment:
      - ENV=PROD
    restart: always
    depends_on:
      - sad-backend
  mongodb:
    image: mongo:latest
    command: mongod --port 27017
    expose:
      - "27017"
    volumes:
      - mongodb_data_container:/data/db
    container_name: mongodb
      
volumes:
  mongodb_data_container:
  nginx_certs: