version: "3.9"

# networks:
#   corp:
#     driver: bridge

services:
  attendance-node1:
    build:
      context: NodeJS\.
      dockerfile: Dockerfile
    container_name: attendance-node1
    # networks:
    #   - corp
    # ports:
    #   - "5000:5000"
    expose:
      - "5000"
    restart: always
    depends_on:
      - mongodb
  nginx:
    container_name: nginx
    # networks:
    #   - corp
    build:
      context: .\Nginx
      dockerfile: Dockerfile
    ports:
      - target: 1000
        published: 1234
        mode: host

      - target: 2000
        published: 4321
        mode: host
    restart: always
    depends_on:
      - 'attendance-node1'
      - 'mongodb'
  mongodb:
    image: mongo:latest
    command: mongod --port 57478
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    # expose:
    #   - "27017"
    expose:
      - "57478"
    # networks:
    #   - corp
    volumes:
      - mongodb_data_container:/data/db
    container_name: mongodb
volumes:
  mongodb_data_container:

  # psqlDB:
  #   image: "postgres" # use latest official postgres version
  #   networks:
  #     - corp
  #   expose:
  #     - 5432
  #   container_name: psqlDB
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=karol
  #     - POSTGRES_PASSWORD=testing123
  #     - POSTGRES_DB=karolk72app
  #   volumes:
  #     - ../../MountData/db:/var/lib/postgresql/data:z # persist data even if container shuts down