version: "3.9"

services:
  attendance-node1:
    build:
      context: NodeJS/.
      dockerfile: Dockerfile
    container_name: attendance-node1
    expose:
      - "5000"
    restart: always
    depends_on:
      - mongodb
    command:
      - node
      - source.js
  nginx:
    container_name: nginx
    build:
      context: Http/.
      dockerfile: Dockerfile
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
        # Temp opened for debugging
      - target: 2000
        published: 4321
        mode: host
    volumes:
      - nginx_certs:/etc/nginx/certs
    restart: always
    depends_on:
      - 'attendance-node1'
      - 'mongodb'
  mongodb:
    image: mongo:latest
    command: mongod --port 27017
    expose:
      - "27017"
    volumes:
      - mongodb_data_container:/data/db
    container_name: mongodb
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - target: 8081
        published: 8081
        mode: host
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongodb:27017/"
    depends_on:
      - mongodb
      
volumes:
  mongodb_data_container:
  nginx_certs:
